#!/bin/bash

if [ $EUID != 0 ] 
	then echo 'Please run as root.'
	exit
fi

echo 'Are you sure you would like to delete all data? This process is irreversible.'
echo 'YES: ENTER'
echo 'NO: CTRL+C'
read
echo "Okay, just wanted to make sure. You want to delete everything. You can't undo this. Are you okay? Do you need to lie down? Are you absolutely SURE?"
echo 'YES: ENTER'
echo 'NO: CTRL+C'
read
echo 'Uh.... okay then!'
rm -rf /bin/OverkillPrivacy
echo /dev/null > overkillPrivacyDD.txt
echo /dev/null > setupFlags.txt
echo 'Overkill Privacy reset to default state. Please run setup to begin again.'
