#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root."
  exit
fi

newPWD=$PWD
echo 'Installing necessary dependencies.'
apt install gpg
pip3 install pydrive
pip3 install emoji
cd /usr/bin
echo 'Making directory OverkillPrivacy in /bin'
mkdir OverkillPrivacy
echo 'Entering /bin/OverkillPrivacy'
cd /usr/bin/OverkillPrivacy
echo 'Creating pass.txt'
touch pass.txt
echo 'Adding nullID to pass file.'
echo "nullId" >> pass.txt
echo 'Creating pwdf.txt'
touch pwdf.txt
echo 'Adding var newPWD to pwd.txt'
echo "$newPWD" >> pwdf.txt
echo 'Creeating story.txt'
touch story.txt
echo 'Generating gpg key'
gpg --gen-key
echo 'Installation finished!'
echo 'Starting OVERKILL PRIVACY'
overkillPrivacyVar=true
cd $newPWD
python3 main.py
