#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root."
  exit
fi

newPWD=$PWD
echo 'Installing necessary dependencies.'
pip3 install pydrive
pip3 install Crypto
cd /usr/bin
echo 'Making directory OverkillPrivacy in /bin'
mkdir OverkillPrivacy
echo 'Entering /bin/OverkillPrivacy'
cd /usr/bin/OverkillPrivacy
echo 'Creating pass.txt'
touch pass.txt
chmod 666 pass.txt
echo 'Adding nullID to pass file.'
echo "nullId" > pass.txt
echo 'Creating pwdf.txt'
touch pwdf.txt
chmod 666 pwdf.txt
echo 'Adding var newPWD to pwd.txt'
echo "$newPWD" > pwdf.txt
echo 'Creating story.txt'
touch story.txt
chmod 666 story.txt
echo 'Creating pubkey.pem'
touch pubkey.pem
chmod 000 pubkey.pem
echo 'Creating prkey.pem'
touch prkey.pem
chmod 000 prkey.pem
echo 'Switching to former working directory'
cd $newPWD
echo 'Writing to setupFlags.txt'
echo 'T' > setupFlags.txt

python3 - << EOF

from Crypto.PublicKey import RSA
import os

keyPath = "/usr/bin/OverkillPrivacy/key.pem"
keyFile = open(keyPath, 'w')
print("Generating RSA keypair")
key = RSA.generate(4096)
print("Creating private key")
privateKey = key.exportKey("PEM")
print("Creating public key")
publicKey = key.publickey().exportKey("PEM")


EOF

echo 'Installation finished!'
echo 'Starting OVERKILL PRIVACY'
overkillPrivacyVar=true
python3 main.py
